# Generated by Django 5.2.7 on 2025-11-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام آیتم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قیمت فعلی')),
                ('ends_at', models.DateTimeField(verbose_name='زمان پایان حراج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'آیتم حراج',
                'verbose_name_plural': 'آیتم\u200cهای حراج',
            },
        ),
    ]
